name: 'Documentation Generator for PHP with phpDocumentor'
description: 'analyzing your PHP source code and DocBlock comments to generate API Documentation'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  dir:
    description: 'Root directory of the project'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
